# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

linearSmPenalty <- function(Y, scalar_mat, M_aug, lambda_s) {
    .Call('_FGLMtrunc_linearSmPenalty', PACKAGE = 'FGLMtrunc', Y, scalar_mat, M_aug, lambda_s)
}

linearpiecePathCpp <- function(Y, n, scalar_mat, M_aug, warmStart, nbasis, weight, lambda_s, lambdaStart, d_active, p_scalar, degree, precision = 1e-3) {
    .Call('_FGLMtrunc_linearpiecePathCpp', PACKAGE = 'FGLMtrunc', Y, n, scalar_mat, M_aug, warmStart, nbasis, weight, lambda_s, lambdaStart, d_active, p_scalar, degree, precision)
}

compute_df_linear <- function(d_active_seq, scalar_mat, M_aug, lambda_s, n) {
    .Call('_FGLMtrunc_compute_df_linear', PACKAGE = 'FGLMtrunc', d_active_seq, scalar_mat, M_aug, lambda_s, n)
}

logisticSmPenalty <- function(Y, scalar_mat, M_aug, lambda_s, warmstart, precision = 1e-6) {
    .Call('_FGLMtrunc_logisticSmPenalty', PACKAGE = 'FGLMtrunc', Y, scalar_mat, M_aug, lambda_s, warmstart, precision)
}

logisticpiecePathCpp <- function(Y, n, scalar_mat, M_aug, warmStart, nbasis, weight, lambda_s, lambdaStart, d_active, p_scalar, degree, precision = 1e-3) {
    .Call('_FGLMtrunc_logisticpiecePathCpp', PACKAGE = 'FGLMtrunc', Y, n, scalar_mat, M_aug, warmStart, nbasis, weight, lambda_s, lambdaStart, d_active, p_scalar, degree, precision)
}

compute_dim_beta_logistic <- function(U_aDU_a, hessian) {
    .Call('_FGLMtrunc_compute_dim_beta_logistic', PACKAGE = 'FGLMtrunc', U_aDU_a, hessian)
}

